### ISSUE TITLE
Issue while training

### ISSUE THREAD

**Issue by danperazzo** [Miffyli/minecraft-bc-2020#1]
Hello, thank you for releasing this wonderful code!

I have an issue during training, that I did not manage to work around:

> AssertionError: Batch size 32 can not be larger than number of episodes 3
Exception ignored in: <bound method HDF5SequenceSampler.__del__ of <dataloaders.hdf5_loader.HDF5SequenceSampler object at 0x7f1bf5c8fcf8>>
Traceback (most recent call last):
  File "/home/daniel/Desktop/minecraft-bc-2020/dataloaders/hdf5_loader.py", line 424, in __del__
    self.close()
  File "/home/daniel/Desktop/minecraft-bc-2020/dataloaders/hdf5_loader.py", line 419, in close
    self.task_queue.close()
AttributeError: 'HDF5SequenceSampler' object has no attribute 'task_queue'

Apparently, the number of episodes is decreasing, and if it is smaller than the batch size, it breaks :/

**Comment by Miffyli** [comment]
Hmm interesting, that should not happen because there _should_ be a task_queue object in the class.

Does this only happen at the very end of training or earlier? I do not have perfect memory of the experiments, but this might be one of those "oh well, it trains the model perfectly, so I can't be bothered to fix this exception" things ^^.

**Comment by danperazzo** [comment]
Hello @Miffyli, maybe it is related to this [issue from the other repo](https://github.com/MichalOp/MineRL2020/issues/1). Now it makes sense it saying that it only has 2 episodes.

**Comment by Miffyli** [comment]
Ah yup, that's the issue! It tries to get more episodes than there is available, so it fails. Downloading full dataset should fix it.

**Comment by danperazzo** [comment]
Yep, now its training, thanks :)
